### ISSUE TITLE
[Default tree] Electro Bolt focus cost lower than normal

### ISSUE THREAD

**Issue by emayal** [LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework#11]
![Sonny_1_and_2_in_2017-Electro_Bolt_Focus](https://github.com/LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework/assets/94645542/ce447a60-e9a0-488c-8f74-85ad08aadc5c)

A level 1 Electro Bolt costs 5 focus, instead of 7 focus in Sonny 1, according to the description. Similarly, a maxed Electro Bolt costs 3 focus instead of 5.

**Comment by LakshmisKshatriya** [comment]
fixed
