### ISSUE TITLE
Add starting abilities to Default tree

### ISSUE THREAD

**Issue by emayal** [LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework#2]
![Sonny_1_and_2_in_2017-Starters](https://github.com/LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework/assets/94645542/0ebf5821-6032-483f-b084-2cd4cd37944a)

If you unequip the starter abilities (Quick Strike & Suppression), then the only way of re-equipping them is to respec because they're not on the Default tree. It would be more convenient to add these to the tree.

**Comment by LakshmisKshatriya** [comment]
![20230713132115_1](https://github.com/LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework/assets/93215080/b8bf599b-ef12-4f7e-bfb8-9aa094e7fb8c)
My idea of adding both abilities
