### ISSUE TITLE
Suggestion: Make passive abilities immediately be in effect when learned

### ISSUE THREAD

**Issue by emayal** [LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework#3]
In the flash games, you didn't have to equip passive abilities on the ability wheel, unlike Sonny 2017. However, in the mod you must equip passive abilities just like vanilla 2017. This requires the player to sacrifice one ability slot which could've been used for an active ability, even more slots would be needed to equip more than one passive. Because it messes with the ability build, I think passives becomes less desireable for the player, and that's why my suggestion is to make passive abilities always active when learnt.

**Comment by LakshmisKshatriya** [comment]
since I managed to do it I will close this issue

**Comment by LakshmisKshatriya** [comment]
* (1f + this.caster.ShieldMod4)
