### ISSUE TITLE
More information in pop-up

### ISSUE THREAD

**Issue by emayal** [LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework#4]
![Sonny_1_and_2_in_2017-Pop_up](https://github.com/LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework/assets/94645542/86ae8851-abde-4bee-b50e-2b3fbf92cea4)

It would be nice to see Focus or Health costs on the pop-ups when you hover over an ability in battle. More detailed info such as scalings would also be nice.

**Comment by LakshmisKshatriya** [comment]
![grafik](https://github.com/LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework/assets/93215080/739c2728-4f9a-48b3-be32-33e6b3903268)
in combat Focus cost + Power Scaling
