### ISSUE TITLE
Default tip text

### ISSUE THREAD

**Issue by emayal** [LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework#9]
![Sonny_1_and_2_in_2017-Tip_Text](https://github.com/LakshmisKshatriya/Sonny-1-2-in-Sonny-2017-Rework/assets/94645542/264e1ed7-d8d4-487b-beca-653f66b58bb9)

When you lose some fights, you get a tip text that literally says "Tip text." While this is a bit humorous, it might be better to let the default tip texts show up just like in vanilla 2017.

**Comment by LakshmisKshatriya** [comment]
Fixed it
